### PR TITLE
Add MetricExportDatadogConfig & MetricExportCloudWatchConfig resources

### PR DESCRIPTION
**Pull request by jenngeorge**
Add a new MetricExportDatadogConfig resource, which manages 
the Datadog metric export configuration for a cluster. 
Add a new MetricExportCloudWatchConfig resource, which manages 
the AWS CloudWatch metric export configuration for a cluster.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93)

### CODE REVIEW

**Comment by jenngeorge** [comment]
Here is a [crl google doc with manual testing examples](https://docs.google.com/document/d/1gOZ-pL449kt71VqQy_WF7x4-MBgOSq6kxIJbKGkgnGc/edit?usp=sharing)

**Review by erademacher — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93)* status: 12 of 15 files reviewed, 5 unresolved discussions (waiting on @jenngeorge)

___
*[`examples/resources/cockroach_metric_export_cloudwatch_config/cockroach_metric_export_cloudwatch_config.tf` line 13 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NR4zJ9035LVDJAnIFy7:-NR4zJ9035LVDJAnIFy8:b-6m9ajm) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/examples/resources/cockroach_metric_export_cloudwatch_config/cockroach_metric_export_cloudwatch_config.tf#L13)):*
> ```HCL
> variable "log_group_name" {
>   type     = string
>   nullable = false
> ```

This is marked optional, so should it be nullable?
___
*[`examples/workflows/cockroach_metric_export/aws/main.tf` line 3 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NR4z_rjDozaGt8M7ScN:-NR4z_rjDozaGt8M7ScO:b-ptd3wn) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/examples/workflows/cockroach_metric_export/aws/main.tf#L3)):*
> ```HCL
> # Your CockroachDB Organization ID can be found at 
> # https://cockroachlabs.cloud/information
> variable "org_id" {
> ```

You could use the new `cockroach_organization` data source to automatically get the org ID instead.
___
*[`examples/workflows/cockroach_metric_export/aws/main.tf` line 121 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NR5EzEm8D3RsQ2EPbxM:-NR5EzEnEPkT4wDJbluh:b-vk020m) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/examples/workflows/cockroach_metric_export/aws/main.tf#L121)):*
> ```HCL
> 
> # Cross-account AWS IAM role in your AWS account.
> resource "aws_iam_role" "example-role" {
> ```

nit: The precedent we've set is to just use "example" as the ID. Since it's also identified by the resource type, adding a suffix isn't really necessary. Same for the other resources in this file.
___
*[`internal/provider/metric_export_datadog_config_resource.go` line 242 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NRA6FsM9KM6zeAY06My:-NRA6FsM9KM6zeAY06Mz:b-zgagvu) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/internal/provider/metric_export_datadog_config_resource.go#L242)):*
> ```Go
> 	}
> 
> 	// stateApiKey := state.ApiKey.ValueString()
> ```

Commented out code



_Code quote:_
```Go
	// stateApiKey := state.ApiKey.ValueString()
	// // The API response includes only the last 4 digits of the Datadog API key.
	// truncApiKey := apiObj.GetApiKey()
	// if truncApiKey != stateApiKey[len(stateApiKey)-4:] {
	// 	resp.Diagnostics.AddError(
	// 		"Unexpected Datadog API key for Datadog metric export config",
	// 		fmt.Sprintf(
	// 			"the truncated Datadog API key returned for cluster ID %s should be a substring of the full Datadog API key "+
	// 				"in terraform state. Please update terraform state with the correct full Datadog API key.",
	// 			clusterID,
	// 		))
	// 	return
	// }
```

**Review by jenngeorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93)* status: 7 of 16 files reviewed, 4 unresolved discussions (waiting on @erademacher)

___
*[`examples/resources/cockroach_metric_export_cloudwatch_config/cockroach_metric_export_cloudwatch_config.tf` line 13 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NR4zJ9035LVDJAnIFy7:-NRASpYU1C3Sy8hCIlpR:bves986) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/examples/resources/cockroach_metric_export_cloudwatch_config/cockroach_metric_export_cloudwatch_config.tf#L13)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

This is marked optional, so should it be nullable?
</blockquote></details>

Good catch! Fixed.
___
*[`examples/workflows/cockroach_metric_export/aws/main.tf` line 3 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NR4z_rjDozaGt8M7ScN:-NRATxaDDCwB-KsKHWcR:bem8ioz) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/examples/workflows/cockroach_metric_export/aws/main.tf#L3)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

You could use the new `cockroach_organization` data source to automatically get the org ID instead.
</blockquote></details>

Removed because the org ID isn't actually used in this file.
___
*[`examples/workflows/cockroach_metric_export/aws/main.tf` line 121 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NR5EzEm8D3RsQ2EPbxM:-NRATFWQ6L60D0mGu8cj:b-bw8e1h) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/examples/workflows/cockroach_metric_export/aws/main.tf#L121)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

nit: The precedent we've set is to just use "example" as the ID. Since it's also identified by the resource type, adding a suffix isn't really necessary. Same for the other resources in this file.
</blockquote></details>

Updated!
___
*[`internal/provider/metric_export_datadog_config_resource.go` line 242 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-NRA6FsM9KM6zeAY06My:-NRAUDgT-sHIiFA60fyS:b-hgsn3c) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/e64e9e810a7031ec996cabaad9b821051876d4d1/internal/provider/metric_export_datadog_config_resource.go#L242)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

Commented out code
</blockquote></details>

Ah I did not mean to push this, thanks for catching it! Removed.

**Review by erademacher — APPROVED** [review]
:lgtm_strong: Looks great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-:-NRAZJut07Sj1WVjnXih:bx0hnzn)* status: 7 of 16 files reviewed, all discussions resolved

**Review by jenngeorge — COMMENTED** [review]
TFTR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/93#-:-NRAnFDB9OFXlplImBHH:bz5m8k4)* status: 7 of 16 files reviewed, all discussions resolved (waiting on @erademacher)

**Pull request merged**
