### PR TITLE
Prep for 1.11.0 tag

### PR DESCRIPTION
**Pull request by fantapop**
Updates Makefile and Changelog for 1.11.0 tag

**Commit checklist**
- [x] Changelog
- [ ] Doc gen (`make generate`)
- [ ] Integration test(s)
- [ ] Acceptance test(s)
- [ ] Example(s)

### CODE REVIEW

**Comment by fantapop** [comment]
I'll run the Acceptance tests against this branch

**Comment by fantapop** [comment]
There was a failure with the Maintenance Window tests because I ran this before the managed-service deploy went out which added the check that the test is looking for.

```
=== NAME  TestAccMaintenanceWindowResource
    maintenance_window_test.go:164: Step 1/5, expected an error with pattern, no match on: Error running apply: exit status 1
        
        Error: Error setting maintenance window
        
          with cockroach_maintenance_window.teststandard,
          on terraform_plugin_test.tf line 26, in resource "cockroach_maintenance_window" "teststandard":
          26: resource "cockroach_maintenance_window" "teststandard" {
        
        upserting maintenance window for cluster
        98ea579f-d0f1-47a3-87f4-ab50c2e5edf4: upserting maintenance window for
        cluster 98ea579f-d0f1-47a3-87f4-ab50c2e5edf4: pq: insert on table
        "maintenance_windows" violates foreign key constraint
        "maintenance_windows_cluster_id_fkey" (trace ID: 4935058963696080509)
```

I was planning to release the provider today but it would be nice to see a green test run which would mean we have to wait until the managed-service deploy.   @marksoper what do you think?

**Comment by marksoper** [comment]
@fantapop let's wait until the API deployment, assuming it's within 1-2 weeks

**Comment by fantapop** [comment]
There should be a release this week.

**Comment by fantapop** [comment]
The deploy went out today.  I've manually run the failing test against prod and it's now passing. I'm inclined to merge this down without running the full suite again because they'll run once more after tagging.

**Review by rgcase — APPROVED** [review]

**Pull request merged**
