### PR TITLE
Update CC Go SDK to v1.0.0

### PR DESCRIPTION
**Pull request by jenngeorge**
Update CC Go SDK to v1.0.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100)

### CODE REVIEW

**Review by erademacher — APPROVED** [review]
:lgtm: Lint error looks transient. I think you can just retry that job.

> Reviewed 23 of 160 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-:-NSh7QbF7W4SVt_RT9qp:b-etaawy)* status: 26 of 163 files reviewed, all discussions resolved

**Review by jenngeorge — COMMENTED** [review]
Tested the serverless and dedicated cluster workflows against staging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-:-NShL9luE0iYkd0EFw62:b-ljk8fr)* status: 25 of 166 files reviewed, 2 unresolved discussions (waiting on @erademacher)

___
*[`examples/resources/cockroach_aws_private_endpoint_connection/cockroach_aws_private_endpoint_connection.tf` line 5 at r3](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-NShKieB6klOiO68aWNI:-NShKieB6klOiO68aWNJ:bpcb5b8) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/09f781b374e991f5501ac7ce20e38a20b646d296/examples/resources/cockroach_aws_private_endpoint_connection/cockroach_aws_private_endpoint_connection.tf#L5)):*
> ```HCL
> }
> 
> resource "cockroach_private_endpoint_connection" "cockroach" {
> ```

Updated this outdated example.
___
*[`internal/provider/cockroach_cluster_data_source.go` line 108 at r3](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-NShKooo7Kv2r5TNy2JO:-NShKooo7Kv2r5TNy2JP:bwaoecg) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/09f781b374e991f5501ac7ce20e38a20b646d296/internal/provider/cockroach_cluster_data_source.go#L108)):*
> ```Go
> 							Computed: true,
> 						},
> 						"primary": schema.BoolAttribute{
> ```

Updated to support this "primary" field. Without it, `terraform plan` for the dedicated cluster workflow was showing this error:
```
│ Error: Value Conversion Error
│
│   with data.cockroach_cluster.example,
│   on main.tf line 139, in data "cockroach_cluster" "example":
│  139: data "cockroach_cluster" "example" {
│
│ An unexpected error was encountered trying to convert from struct
│ value. This is always an error in the provider. Please report the
│ following to the provider developer:
│
│ couldn't find type information for attribute in supplied attr.Type
│ basetypes.ObjectType
```

**Review by jenngeorge — COMMENTED** [review]
Retrying the lint job wasn't working, but maybe this will help: https://github.com/cockroachdb/terraform-provider-cockroach/pull/101

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-:-NShQcJhCHpej787wFij:b-n8908g)* status: 25 of 166 files reviewed, 2 unresolved discussions (waiting on @erademacher)

**Review by jenngeorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100)* status: 26 of 167 files reviewed, 2 unresolved discussions (waiting on @erademacher)

___
*[`internal/provider/cockroach_cluster_data_source.go` line 108 at r3](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-NShKooo7Kv2r5TNy2JO:-NShUcCz5_jNI7ZFpTdh:b-92k77) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/09f781b374e991f5501ac7ce20e38a20b646d296/internal/provider/cockroach_cluster_data_source.go#L108)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

> │ An unexpected error was encountered trying to convert from struct
> │ value. This is always an error in the provider. Please report the
> │ following to the provider developer:
Oh, do the resource and data source share a model? Could you add a TODO to add a test to make sure the datasource and resource stay in sync?
</blockquote></details>

Yeah, they both use the `CockroachCluster` model. Good idea to test -- added a TODO in this file & a comment to the model.

**Review by jenngeorge — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/100#-:-NShVZgR4xBL_lRAw2hR:b-814g8k)* status: 26 of 167 files reviewed, 2 unresolved discussions (waiting on @erademacher)

**Pull request merged**
