### PR TITLE
EndpointServices resource

### PR DESCRIPTION
**Pull request by erademacher**
- Added a new resource for private endpoint services
- Added tests
- Updated examples
- Regenerated docs
- Cleaned up some cluster error handling as a "while you're in there"

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43)

### CODE REVIEW

**Review by ryanluu12345 — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @erademacher and @prafull01)

___
*[`docs/resources/endpoint_services.md` line 6 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopEie1NSjxVUvfWJi:-NFopEie1NSjxVUvfWJj:b-67mulm) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/docs/resources/endpoint_services.md#L6)):*
> ```Markdown
> subcategory: ""
> description: |-
>   Private endpoint service
> ```

Are descriptions in Terraform usually meant to be concise. Or could we be more detailed here? `PrivateEndpointService` refers to the services that allow for VPC communication, either via PrivateLink (AWS) or Peering (GCP).
___
*[`docs/resources/endpoint_services.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopWcc4vue0EBftOC7:-NFopWcc4vue0EBftOC8:b-ca5b3q) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/docs/resources/endpoint_services.md#L42)):*
> ```Markdown
> Read-Only:
> 
> - `availability_zone_ids` (List of String)
> ```

Maybe want to make a note that the `availability_zone_ids` specify which AZ IDs customers should create their VPCs in to minimize their cost. @abhinavg6 can confirm this.
___
*[`internal/provider/cluster_resource.go` line 547 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopx9DCsOGxa8BrSiJ:-NFopx9DCsOGxa8BrSiK:b67sgtx) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/cluster_resource.go#L547)):*
> ```Go
> 		clusterObj, httpResp, err := cl.GetCluster(ctx, id)
> 		if err != nil {
> 			if httpResp.StatusCode < http.StatusInternalServerError {
> ```

Clever!
___
*[`internal/provider/endpoint_services_resource.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoqR2B2XnQv3tDYfBl:-NFoqR2B2XnQv3tDYfBm:b-d1sb84) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/endpoint_services_resource.go#L221)):*
> ```Go
> 
> func (n endpointServicesResource) Update(_ context.Context, _ tfsdk.UpdateResourceRequest, _ *tfsdk.UpdateResourceResponse) {
> 	// no-op - Endpoint services cannot be updated
> ```

Why do we not add a warning or info message to the user about how `Update` cannot be applied? If I am not mistaken, this would just no-op silently right?
___
*[`internal/provider/endpoint_services_resource.go` line 236 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoswEP46bEWb1b0yuo:-NFoswEP46bEWb1b0yup:b9tbste) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/endpoint_services_resource.go#L236)):*
> ```Go
> 
> func (n endpointServicesResource) ImportState(ctx context.Context, req tfsdk.ImportResourceStateRequest, resp *tfsdk.ImportResourceStateResponse) {
> 	tfsdk.ResourceImportStatePassthroughID(ctx, tftypes.NewAttributePath().WithAttributeName("cluster_id"), req, resp)
> ```

What exactly will this do? Will it attempt to import over endpoint services from the cluster?
___
*[`internal/provider/models.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoqvUE0BpR4fAHSfId:-NFoqvUE0BpR4fAHSfIe:bjjn8wm) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/models.go#L95)):*
> ```Go
> 
> // AWSPrivateLinkServiceDetail struct for AWSPrivateLinkServiceDetail.
> type AWSPrivateLinkServiceDetail struct {
> ```

Nit: Maybe to keep it consistent since it's a subresource of `PrivateEndpointService`, consider `PrivateEndpointServiceAWSDetail`? Although, I think the way you have it makes it explicit that you're referring to AWS PrivateLink details.

**Review by erademacher — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @abhinavg6, @prafull01, and @ryanluu12345)

___
*[`docs/resources/endpoint_services.md` line 6 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopEie1NSjxVUvfWJi:-NFozh6N2XOLsL3d2XKt:b5fka3x) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/docs/resources/endpoint_services.md#L6)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Are descriptions in Terraform usually meant to be concise. Or could we be more detailed here? `PrivateEndpointService` refers to the services that allow for VPC communication, either via PrivateLink (AWS) or Peering (GCP).
</blockquote></details>

I think we can be as verbose as we want here. Updated!
___
*[`docs/resources/endpoint_services.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopWcc4vue0EBftOC7:-NFozm3Y39U2Rbk2L8ZK:b-soga60) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/docs/resources/endpoint_services.md#L42)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Maybe want to make a note that the `availability_zone_ids` specify which AZ IDs customers should create their VPCs in to minimize their cost. @abhinavg6 can confirm this.
</blockquote></details>

Added a tentative description.
___
*[`internal/provider/cluster_resource.go` line 547 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopx9DCsOGxa8BrSiJ:-NFozrly8_ytPV_GwL3m:b32vhw) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/cluster_resource.go#L547)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Clever!
</blockquote></details>

:)
___
*[`internal/provider/endpoint_services_resource.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoqR2B2XnQv3tDYfBl:-NFozwmP2O3psb4YvEPf:bp11217) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/endpoint_services_resource.go#L221)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Why do we not add a warning or info message to the user about how `Update` cannot be applied? If I am not mistaken, this would just no-op silently right?
</blockquote></details>

Because there's nothing a user can actually do to trigger an update. All fields are either computed-only or require a rebuild. Currently, this code is unreachable.
___
*[`internal/provider/endpoint_services_resource.go` line 236 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoswEP46bEWb1b0yuo:-NFp-533AIE6W4MRyO-s:b8630q4) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/endpoint_services_resource.go#L236)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

What exactly will this do? Will it attempt to import over endpoint services from the cluster?
</blockquote></details>

Yep, this is if you have an existing cluster with endpoint services set up. You can call `terraform import` and pass in the cluster ID to pull the state in and manage it with Terraform.
___
*[`internal/provider/models.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoqvUE0BpR4fAHSfId:-NFp-HgN4mEguE-WfzKx:b-bw8e14) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/models.go#L95)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Nit: Maybe to keep it consistent since it's a subresource of `PrivateEndpointService`, consider `PrivateEndpointServiceAWSDetail`? Although, I think the way you have it makes it explicit that you're referring to AWS PrivateLink details.
</blockquote></details>

Updated.

**Review by erademacher — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @abhinavg6, @prafull01, and @ryanluu12345)

___
*[`docs/resources/endpoint_services.md` line 6 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFopEie1NSjxVUvfWJi:-NFp7fUp315pSfzO7J1U:b37f317) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/docs/resources/endpoint_services.md#L6)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

I think we can be as verbose as we want here. Updated!
</blockquote></details>

Forgot to regenerate the docs. Actually updated now.

**Comment by marksoper** [comment]
*[`internal/provider/endpoint_services_resource.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoqR2B2XnQv3tDYfBl:-NFpetiK3PTDurVYHUai:bpdtmxw) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/endpoint_services_resource.go#L221)):*
<details><summary><i>Previously, erademacher (Evan Rademacher) wrote…</i></summary><blockquote>

Because there's nothing a user can actually do to trigger an update. All fields are either computed-only or require a rebuild. Currently, this code is unreachable.
</blockquote></details>

This makes sense. Customers can enable (all) services by declaring the "Services" resource. What happens if they remove the Services resource and run apply - they would get an error right?

**Review by marksoper — APPROVED** [review]

**Review by prafull01 — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43)* status: all files reviewed, 8 unresolved discussions (waiting on @abhinavg6, @erademacher, and @ryanluu12345)

___
*[`internal/provider/private_endpoint_services_resource.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFryqn_CoquspUrIIL7:-NFryqn_CoquspUrIIL8:bwx2olh) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/bc369b069cc406a7ef05119fa90d4bc9ef250a64/internal/provider/private_endpoint_services_resource.go#L42)):*
> ```Go
> 				Type:     types.StringType,
> 				PlanModifiers: tfsdk.AttributePlanModifiers{
> 					tfsdk.RequiresReplace(),
> ```

Just FYI: The require replace will call delete of PrivateEndpointService with old cluster and create a new PrivateEndpointService with new cluster id which user has provided. This is the behaviour we want right?



_Code quote:_
```Go
				PlanModifiers: tfsdk.AttributePlanModifiers{
					tfsdk.RequiresReplace(),
				},
```
___
*[`internal/provider/private_endpoint_services_resource.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFsJ09iE_37SJkk9dMQ:-NFsJ09iE_37SJkk9dMR:b-8a53k) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/bc369b069cc406a7ef05119fa90d4bc9ef250a64/internal/provider/private_endpoint_services_resource.go#L139)):*
> ```Go
> 		return
> 	}
> ```

I think this is PrivateEndPoint service is for AWS dedicated cluster only. We should error out if the cluster id provided by user is of GCP.

**Review by erademacher — COMMENTED** [review]
TFTRs! I'm going to go ahead and merge since we're on a bit of a time crunch here. If there's additional feedback, I'm happy to address it in a followup.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-:-NFtFoYQ-tFZEwLi1fic:b-s7aeik)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @abhinavg6, @prafull01, and @ryanluu12345)

___
*[`internal/provider/endpoint_services_resource.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFoqR2B2XnQv3tDYfBl:-NFtFcEL2wKtYgCCE6Ia:bg2pkle) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/4192aa6a9da255b477abbb031071f40e3a622cfe/internal/provider/endpoint_services_resource.go#L221)):*
<details><summary><i>Previously, marksoper (Mark Soper) wrote…</i></summary><blockquote>

This makes sense. Customers can enable (all) services by declaring the "Services" resource. What happens if they remove the Services resource and run apply - they would get an error right?
</blockquote></details>

Warning, not error. That would delete the resource, which is a no-op on the API side.
___
*[`internal/provider/private_endpoint_services_resource.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFryqn_CoquspUrIIL7:-NFtFOh6ABPUA31QpJcD:b-c5xc1b) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/bc369b069cc406a7ef05119fa90d4bc9ef250a64/internal/provider/private_endpoint_services_resource.go#L42)):*
<details><summary><i>Previously, prafull01 (Prafull Ladha) wrote…</i></summary><blockquote>

Just FYI: The require replace will call delete of PrivateEndpointService with old cluster and create a new PrivateEndpointService with new cluster id which user has provided. This is the behaviour we want right?
</blockquote></details>

Yep, that's what we want. Users can always recreate the resource if they want, and the API will handle it gracefully.
___
*[`internal/provider/private_endpoint_services_resource.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43#-NFsJ09iE_37SJkk9dMQ:-NFtFUMsADaxp4WODhLc:bki4e9d) ([raw file](https://github.com/cockroachdb/terraform-provider-cockroach/blob/bc369b069cc406a7ef05119fa90d4bc9ef250a64/internal/provider/private_endpoint_services_resource.go#L139)):*
<details><summary><i>Previously, prafull01 (Prafull Ladha) wrote…</i></summary><blockquote>

I think this is PrivateEndPoint service is for AWS dedicated cluster only. We should error out if the cluster id provided by user is of GCP. 
</blockquote></details>

Good call. Added another check.

**Review by prafull01 — COMMENTED** [review]
> Reviewed 3 of 10 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/43)* status: all files reviewed, 6 unresolved discussions

**Pull request merged**
