### PR TITLE
Fix updating ip allowlist state 

### PR DESCRIPTION
**Pull request by yecs1999**
Fixes https://github.com/cockroachdb/terraform-provider-cockroach/issues/86

### CODE REVIEW

**Comment by erademacher** [comment]
Could you add a regression test, please? You can parameterize `getTestAllowlistEntryResourceConfig` and change the flag and name values in another test step. Take a look at `testDatabaseResource` for an example of a two-step test.

We don't have many update tests because they tend to be long and flaky, but allowlist entry changes should be pretty quick.

If you don't have time, I can handle it.

**Comment by yecs1999** [comment]
@erademacher i'm still getting an error on the integration test after adding a second step
```
    cluster_resource.go:353: Unexpected call to *mock_client.MockService.GetCluster([context.Background.WithValue(type transport.connectionKey, val <not Stringer>).WithValue(type peer.peerKey, val <not Stringer>).WithCancel.WithValue(type metadata.mdIncomingKey, val <not Stringer>).WithValue(type grpc.streamKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>).WithCancel.WithValue(type tf6serverlogging.ContextKeyDownstreamRequestStartTime, val 2023-03-09 00:02:26.160444699 +0000 UTC m=+5.378243490).WithCancel.WithValue(type logging.loggerKey, val <not Stringer>).WithValue(type logging.loggerKey, val <not Stringer>) 00000000-0000-0000-0000-000000000000]) at /home/runner/work/terraform-provider-cockroach/terraform-provider-cockroach/internal/provider/cluster_resource.go:353 because: 
        expected call at /home/runner/work/terraform-provider-cockroach/terraform-provider-cockroach/internal/provider/networking_resource_test.go:101 has already been called the max number of times
panic: test timed out after 5m0s
```

**Review by erademacher — APPROVED** [review]
@yecs1999 I finished the tests. Mostly just needed to update the mock calls.
:shipit: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/terraform-provider-cockroach/87#-:-NQS4Dn_ApHRIU6yolF4:b-cakgum)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jenngeorge)

**Comment by yecs1999** [comment]
Thanks!

**Pull request merged**
