### PR TITLE
convert from provisioned_capacity to provisioned_vcpus

### PR DESCRIPTION
**Pull request by andy-kimball**
Rename the `provisioned_capacity` field to `provisioned_vcpus` and update all
tests and examples to use the vCPUs unit rather than request units by dividing
by 500. This is part of the overall migration to vCPUs for Cloud 2.0.

**Commit checklist**
- [X] Changelog
- [X] Doc gen (`make generate`)
- [X] Integration test(s)
- [X] Acceptance test(s)
- [X] Example(s)

### CODE REVIEW

**Comment by andy-kimball** [comment]
Similar to the SDK PR, I will hard reset the `cloud-20` branch to `main` and then apply this sequence of commits to that branch.

IMPORTANT: All but the last commit are older commits that are being reapplied to a new base. All of the older commits have already been reviewed. While I did need to make a few tweaks to those to get past some merge conflicts, there are no material changes. I'd advise only reviewing the last commit.

**Comment by andy-kimball** [comment]
Also, I won't merge this PR until all of the required API changes are in production (it seems we're still pretty far behind in our rollouts).

**Review by rgcase — APPROVED** [review]
I only looked at the last commit but this seems fine. Will we cut a new version of the Cloud 2.0 TF provider for this?

**Comment by andy-kimball** [comment]
I will hard reset the current version of the Cloud 2.0 TF provider to this commit. Only Private Preview customers have been using this, but they will need to switch any config they have to use `provisioned_vcpus` rather than `provisioned_capacity`.

**Pull request merged**
