### PR TITLE
vendor: upgrade cockroach-cloud-sdk-go to v1.8.0

### PR DESCRIPTION
**Pull request by carloruiz**
There are breaking changes in the new cockroach-sdk version. This commit includes the required code changes.

**Commit checklist**
- [x] Changelog
- [x] Doc gen (`make generate`)
- [x] Integration test(s)
- [x] Acceptance test(s)
- [ ] Example(s)

### CODE REVIEW

**Comment by carloruiz** [comment]
Acceptance tests for `database` resource passed. 
```
$ COCKROACH_API_KEY=<KEY> COCKROACH_SERVER=https://management-staging.crdb.io TF_ACC=1 make test
go test ./... -run TestAccDatabaseResource -v  -timeout 20m
?   	github.com/cockroachdb/terraform-provider-cockroach	[no test files]
?   	github.com/cockroachdb/terraform-provider-cockroach/mock	[no test files]
=== RUN   TestAccDatabaseResource
=== PAUSE TestAccDatabaseResource
=== CONT  TestAccDatabaseResource
--- PASS: TestAccDatabaseResource (32.15s)
PASS
ok  	github.com/cockroachdb/terraform-provider-cockroach/internal/provider	32.547s
```

This is the serverless cluster created as part of that test
```
root@localhost:26257/management_console_production> select * from clusters where name = 'tftest-database-spun';                               
-[ RECORD 1 ]
id                                      | 7cc4e495-6f8b-420c-8a07-fb34ae15591a
organization_id                         | b8a9e812-9c29-4e30-ba28-ca3b83419438
name                                    | tftest-database-spun
environment                             | Staging
created_at                              | 2024-03-10 03:20:26.044685+00
updated_at                              | 2024-03-10 03:20:26.044685+00
creator_id                              | 0d7b5f3f-de40-4c85-8863-145f8177d56d
billing_plan                            | invoice
trial_duration                          | NULL
plan_option_id                          | 00000000-0000-0000-0000-000000000000
pricing_code                            | 2021-12-01
tier                                    | NULL
has_private_nodes                       | f
sso_enabled                             | f
cmek_key_strategy                       | MULTI_KEY
trusted_private_endpoint_owners_enabled | f
```
^ Doesn't really feel right to me. Will let someone from serverless take a look on Monday.

**Comment by carloruiz** [comment]
No CHANGELOG worthy changes IMO since nothing user-impacting.

**Review by fantapop — APPROVED** [review]
Seems good to me.  I left one comment about the copyright date but I don't think that needs to be fixed here.

**Comment by carloruiz** [comment]
> Can you be more specific? What doesn't feel right?

That tier and plan option id were not set.

**Comment by rgcase** [comment]
> The tier is a computed property right now. I don't think the field is set in the `clusters` table. The plan option ID is old and deprecated. Probably both fields need to be dropped. @rgcase would know more.

Yep this is all true.

**Pull request merged**
